nameOverride:
fullnameOverride:
# --------------- common --------------
commonLabels:
commonAnnotations:
# ----------- initContainers ----------
volumePermissions:
  enabled: false
# ------ volumes and volumeMounts -----
persistence:
  enabled: false
# ----------- command/debug -----------
diagnosticMode:
  enabled: false
  # command:
  #   - sleep
  # args:
  #   - infinity
# --------- MAIN_OBJECT_BLOCK ---------
configValues:
  deploymentAnnotations:
    # collectord.io/index: '' # PROVIDE SPLUNK INDEX
  autoscaling:
    enabled: false
  replicaCount: 1
  podAnnotations:
    enabled: true
    resetOnConfigChange: true
    annotations:
  prometheus:
    scrape: false
  metrics:
    enabled: false
  tracing:
    enabled: false
  # topologySpreadConstraints:
  #   - maxSkew: 1
  #     topologyKey: zone
  #     whenUnsatisfiable: DoNotSchedule
  #     labelSelector:
  #       matchLabels:
  #         app.kubernetes.io/name: '{{ include "common.names.name" . }}'
  podSecurityContext:
    enabled: false
  # ----------- containers ------------
  image:
    repository: app/mc-web-tools
    tag: v1.0.0
    pullPolicy: Always
    debug: false
  containerSecurityContext:
    enabled: true
    allowPrivilegeEscalation: false
    # runAsUser: 0
  extraEnvVars:
    - name: SERVER_PORT
      value: '{{ .Values.configValues.containerPorts.http }}'
  extraEnvVarsCM: '{{ template "common.names.fullname" . }}'
  extraEnvVarsSecret:
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 50m
      memory: 500Mi
  containerPorts:
    http: 8080
    https: 443
  customLivenessProbe:
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
    httpGet:
      path: /env-config.js
      port: http
  customReadinessProbe:
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
    httpGet:
      path: /env-config.js
      port: http
  startupProbe:
    enabled: false
  extraVolumeMounts:
    - name: nginx-config
      mountPath: /etc/nginx/conf.d/default.conf
      subPath: default.conf
  extraVolumes:
    - name: nginx-config
      configMap:
        name: '{{ template "common.names.fullname" . }}'
        items:
          - key: default.conf
            path: default.conf
env:
  logLevel: info
  logPrettyPrintEnabled: false
  responseCompressionEnabled: true
  requestPayloadLimit: 1mb
  publicUrl: /tools
  map:
    center: '[34.811, 31.908]'
    zoom: 7
  baseMaps: ''
  defaultTerrainProviderUrl: ''
  apps: ''
  csw3DUrl: ''
  shouldShowPrecisionDisclaimer: 'כלי ניתוח השטח טרם עברו חק״ב - אין להסתמך על הנתונים <b>לשימושים מבצעיים</b>!'
route:
  enabled: true
  annotations:
    haproxy.router.openshift.io/rewrite-target: /
  timeout:
    enabled: false
    duration: 60s
  routesMapping:
    - hostname:
      path: /tools
      suffix:
  targetPort: http
  tls:
    enabled: true
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
    useCerts: true
  extraRules:
ingress:
  enabled: false
  apiVersion:
  type: nginx-kubernetes
  annotations:
  pathType: Prefix
  hostname: libot.wwest.local
  extraHosts: []
  extraPaths: []
  path: /tools
  extraRules: []
  extraTls: []
  selfSigned: false
  tls: true
  cors:
    enabled: true
    origin: '*'
service:
  annotations:
  ports:
    http: 80
  protocol: TCP
serviceAccount:
  create: false
